CREATE DATABASE METAGENOMESIMG;

USE METAGENOMESIMG;

CREATE TABLE metadata
(
    META_ID DECIMAL(10) NOT NULL,
    MICROBIOME_NAME VARCHAR(255),
    NCBI_TAXON_ID VARCHAR(6),
    ADD_DATE VARCHAR(10),
    MODIFIED_DATE VARCHAR(10),
    ISOLATION_COUNTRY VARCHAR(50),
    ISOLATION VARCHAR(200),
    ISOLATION_YEAR VARCHAR(50),
    LATITUDE VARCHAR(20),
    LONGITUDE VARCHAR(20),
    ALTITUDE VARCHAR(20),
    SEQUENCING_STATUS VARCHAR(20),
    PH VARCHAR(30),
    TEMPERATURE_RANGE VARCHAR(50),
    OXYGEN_REQUIREMENT VARCHAR(20),
    PRIMARY KEY(META_ID),
    HABITAT_SUPERTYPE VARCHAR(50),
    HABITAT_TYPE VARCHAR(50),
    HABITAT_SUBTYPE VARCHAR(50),
    HABITAT_EXTRA VARCHAR(50)
);


CREATE TABLE genes
(
    METAID DECIMAL(10) NOT NULL,
    GENEID DECIMAL(10) NOT NULL,
    COG VARCHAR(15),
    EC VARCHAR(20),
    KEGG VARCHAR(20),
    SEED VARCHAR(20),
    LOCUS_TYPE VARCHAR(20),
    PFAM VARCHAR(20),
    PRIMARY KEY(METAID, GENEID),
    FOREIGN KEY (METAID) 
    REFERENCES metadata(META_ID) 
    ON DELETE CASCADE
);

CREATE TABLE sequences
(
    METAID DECIMAL(10) NOT NULL,
    GENEID DECIMAL(10) NOT NULL,
    SEQAA TEXT,
    SEQNT TEXT,
    PRIMARY KEY(METAID, GENEID),
    FOREIGN KEY (METAID) 
    REFERENCES genes(METAID) 
    ON DELETE CASCADE
);

CREATE TABLE cog_categories
(
	COG VARCHAR(10),
	COG_DESCRIPTION VARCHAR(120),
	COG_CATEGORY VARCHAR(1),
        INDEX(COG)
);

CREATE TABLE count_cogs
(
    METAID DECIMAL(10) NOT NULL,
    COG VARCHAR(10) NOT NULL,
    COG_CATEGORY VARCHAR(1),
    COUNT_COG DECIMAL(10) NOT NULL,
    PRIMARY KEY(METAID,COG),
    INDEX(COG),
    INDEX(COG_CATEGORY),
    INDEX(METAID),
    FOREIGN KEY (METAID) 
    REFERENCES genes(METAID) 
    ON DELETE CASCADE
);
